const {contextBridge, ipcRenderer, shell} = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
    installJDK: (version) => ipcRenderer.invoke('install-jdk', version),
    installFromLocal: (version) => ipcRenderer.invoke('install-from-local', version),
    importLocalJDK: (filePath) => ipcRenderer.invoke('import-local-jdk', filePath),
    checkJDK: () => ipcRenderer.invoke('check-jdk'),
    switchJDK: (version) => ipcRenderer.invoke('switch-jdk', version),
    deleteJDK: (version) => ipcRenderer.invoke('delete-jdk', version),
    cancelDownload: () => ipcRenderer.send('cancel-download'),
    onDownloadProgress: (callback) => ipcRenderer.on('download-progress', (_, data) => callback(data)),
    onJDKChanged: (callback) => ipcRenderer.on('jdk-changed', callback),

    installPython: (version, mirror) => ipcRenderer.invoke('install-python', version, mirror),
    installFromLocalPython: (version, mirror) => ipcRenderer.invoke('install-from-local-python', version, mirror),
    importLocalPython: (filePath) => ipcRenderer.invoke('import-local-python', filePath),
    checkPython: () => ipcRenderer.invoke('check-python'),
    switchPython: (version) => ipcRenderer.invoke('switch-python', version),
    deletePython: (version) => ipcRenderer.invoke('delete-python', version),
    cancelPythonDownload: () => ipcRenderer.send('cancel-python-download'),
    onPythonChanged: (callback) => ipcRenderer.on('python-changed', callback),

    installMySQL: (version, password) => ipcRenderer.invoke('install-mysql', version, password),
    installFromLocalMySQL: (version, password) => ipcRenderer.invoke('install-from-local-mysql', version, password),
    importLocalMySQL: (filePath) => ipcRenderer.invoke('import-local-mysql', filePath),
    checkMySQL: () => ipcRenderer.invoke('check-mysql'),
    switchMySQL: (version) => ipcRenderer.invoke('switch-mysql', version),
    deleteMySQL: (version) => ipcRenderer.invoke('delete-mysql', version),
    startMySQLService: (version) => ipcRenderer.invoke('start-mysql-service', version),
    stopMySQLService: (version) => ipcRenderer.invoke('stop-mysql-service', version),
    restartMySQLService: (version) => ipcRenderer.invoke('restart-mysql-service', version),
    getMySQLServiceStatus: (version) => ipcRenderer.invoke('get-mysql-service-status', version),
    changeMySQLPassword: (version, oldPassword, newPassword) => ipcRenderer.invoke('change-mysql-password', version, oldPassword, newPassword),
    cancelMySQLDownload: () => ipcRenderer.send('cancel-mysql-download'),
    onMySQLProgress: (callback) => ipcRenderer.on('mysql-progress', (_, data) => callback(data)),
    onMySQLChanged: (callback) => ipcRenderer.on('mysql-changed', callback),

    installRedis: (version, password, maxmemory, customPort) => ipcRenderer.invoke('install-redis', version, password, maxmemory, customPort),
    installFromLocalRedis: (version, password, maxmemory, customPort) => ipcRenderer.invoke('install-from-local-redis', version, password, maxmemory, customPort),
    importLocalRedis: (filePath) => ipcRenderer.invoke('import-local-redis', filePath),
    checkRedis: () => ipcRenderer.invoke('check-redis'),
    switchRedis: (version) => ipcRenderer.invoke('switch-redis', version),
    deleteRedis: (version) => ipcRenderer.invoke('delete-redis', version),
    startRedisService: (version) => ipcRenderer.invoke('start-redis-service', version),
    stopRedisService: (version) => ipcRenderer.invoke('stop-redis-service', version),
    restartRedisService: (version) => ipcRenderer.invoke('restart-redis-service', version),
    getRedisServiceStatus: (version) => ipcRenderer.invoke('get-redis-service-status', version),
    getRedisConfig: (version) => ipcRenderer.invoke('get-redis-config', version),
    changeRedisPassword: (version, oldPassword, newPassword) => ipcRenderer.invoke('change-redis-password', version, oldPassword, newPassword),
    cancelRedisDownload: () => ipcRenderer.send('cancel-redis-download'),
    onRedisProgress: (callback) => ipcRenderer.on('redis-progress', (_, data) => callback(data)),
    onRedisChanged: (callback) => ipcRenderer.on('redis-changed', callback),

    checkPort: (port) => ipcRenderer.invoke('check-port', port),

    installMaven: (useLocal) => ipcRenderer.invoke('install-maven', useLocal),
    importLocalMaven: (filePath) => ipcRenderer.invoke('import-local-maven', filePath),
    checkMaven: () => ipcRenderer.invoke('check-maven'),
    uninstallMaven: () => ipcRenderer.invoke('uninstall-maven'),
    cancelMavenDownload: () => ipcRenderer.send('cancel-maven-download'),
    onMavenProgress: (callback) => ipcRenderer.on('maven-progress', (_, data) => callback(data)),
    onMavenChanged: (callback) => ipcRenderer.on('maven-changed', callback),

    getSystemStats: () => ipcRenderer.invoke('get-system-stats'),

    getCacheSize: () => ipcRenderer.invoke('get-cache-size'),
    clearCache: () => ipcRenderer.invoke('clear-cache'),
    clearLogs: () => ipcRenderer.invoke('clear-logs'),
    getVersionInfo: () => ipcRenderer.invoke('get-version-info'),
    openGitHub: () => ipcRenderer.invoke('open-github'),
    setProxy: (proxy) => ipcRenderer.invoke('set-proxy', proxy),

    getUsername: () => ipcRenderer.invoke('get-username'),

    openExternal: (url) => shell.openExternal(url),
    getUserDataPath: () => ipcRenderer.invoke('get-user-data-path'),
    openFileDialog: (options) => ipcRenderer.invoke('open-file-dialog', options),
    checkPathExists: (path) => ipcRenderer.invoke('check-path-exists', path)
});